stages:
  prepare:
    cmd: python -m prodml.data
    deps:
      - data/raw/balanced-reviews.txt
      - src/prodml/data.py
      - src/prodml/features.py
    outs:
      - data/processed/

  train:
    cmd: python -m prodml.train
    deps:
      - data/processed/
      - src/prodml/train.py
    params:
      - config.yaml:model
    outs:
      - models/sentiment_model.pkl
      - models/vectorizer.pkl
    metrics:
      - metrics/train_metrics.json:
          cache: false
